package utils.keys;

public class KeyReferences {


    //SETTINGS Window--> cardplay_poker.cp_user_settings
    public final static String SETTINGS_TOURNEY_FILTER = "TOURNEY FILTER";

    public enum SETTINGS {

        ACTION_ALL_IN, ACTION_BET_RAISE, ACTION_BET_RAISE_BUTTON_1, ACTION_BET_RAISE_BUTTON_2, ACTION_BET_RAISE_BUTTON_3, ACTION_BET_RAISE_BUTTON_4, ACTION_BET_RAISE_BUTTON_5, ACTION_BET_RAISE_BUTTON_6, ACTION_BET_RAISE_BUTTON_7, ACTION_BET_RAISE_FIVE_X_CALL, ACTION_BET_RAISE_HALF_POT, ACTION_BET_RAISE_POT, ACTION_BET_RAISE_THREE_FOURTH_POT, ACTION_BET_RAISE_THREE_X_CALL, ACTION_BET_RAISE_TWO_THIRD_POT, ACTION_BET_RAISE_TWO_X_CALL, ACTION_CHECK_CALL, ACTION_FOLD, App_BIG_BLIND_ENABLE, APP_POST_FLOP_BUTTON1, APP_POST_FLOP_BUTTON2, APP_POST_FLOP_BUTTON3, APP_POST_FLOP_BUTTON4, APP_PRE_FLOP_BUTTON1, APP_PRE_FLOP_BUTTON2, APP_PRE_FLOP_BUTTON3, APP_PRE_FLOP_BUTTON4, bcardtype, BET_SOUND, CALL_SOUND, cardtype, CHECK_SOUND, COMM_CARDS_SOUND, EXPR_ANIM_ENABLE, FOLD_SOUND, FOUR_COLOR_DECK, hideempty, hidefull, HOLE_CARDS_SOUND, IOS_IS_FINAL_TABLE, IOS_TABLE_BG, IOS_TABLE_OUTER_BG, IS_FINAL_TABLE, IS_TOURNEY_FILTER, ITEM_ANIM_ENABLE, listView, MTT_ENDED, MTT_FO, MTT_FREEROL, MTT_HOLDEM, MTT_KO, MTT_LT_REG, MTT_OMAHA, MTT_PLAYING, MTT_RANG, MTT_REAL, MTT_REBUY, MTT_REGISTERD, MTT_REGISTERING, MTT_RENTRY, MTT_RUNNING, MTT_SAT, MTT_TKT, MUTE_ALL, NGDESK_POSTFLOP_BUTTON1, NGDESK_POSTFLOP_BUTTON2, NGDESK_POSTFLOP_BUTTON3, NGDESK_POSTFLOP_BUTTON4, NGDESK_POSTFLOP_BUTTON5, NGDESK_POSTFLOP_BUTTON6, NGDESK_POSTFLOP_BUTTON7, NGDESK_PREFLOP_BUTTON1, NGDESK_PREFLOP_BUTTON2, NGDESK_PREFLOP_BUTTON3, NGDESK_PREFLOP_BUTTON4, NGDESK_PREFLOP_BUTTON5, NGDESK_PREFLOP_BUTTON6, NGDESK_PREFLOP_BUTTON7, NGMOB_POSTFLOP_BUTTON1, NGMOB_POSTFLOP_BUTTON2, NGMOB_POSTFLOP_BUTTON3, NGMOB_POSTFLOP_BUTTON4, NGMOB_PREFLOP_BUTTON1, NGMOB_PREFLOP_BUTTON2, NGMOB_PREFLOP_BUTTON3, NGMOB_PREFLOP_BUTTON4, NG_AUTO_ADD_CHIPS, NG_AUTO_BUY_IN, NG_AUTO_BUY_IN_BB, NG_AUTO_FOCUS_USER_TURN, NG_AUTO_REBUY, NG_AUTO_REBUY_IN_FORM, NG_BACKGROUND_COLOR, NG_BET_SLIDER_BLIND, NG_CARD_BACKGROUND, NG_FAV_3BET, NG_FAV_3BETFOLD, NG_FAV_ATTEMPTTOSTEAL, NG_FAV_CBET, NG_FAV_CBETFOLD, NG_FAV_PFR, NG_FAV_STEAL, NG_FAV_VPIP, NG_FAV_WSD, NG_FAV_WTSD, NG_FINAL_TABLE_THEME, NG_HIDE_ENDED, NG_HIDE_ME_FIND_PLAYER, NG_IMP_INFO, NG_OWN_CHAT_BALLOONS, NG_PLAYER_BALLOONS, NG_SHOW_COMBO_VIEW, NG_SHOW_MY_JOINED, NG_TABLE_COLOR, NG_TOUR_DONE, NG_VIP_INFO, QUICK_BLINDS, QUICK_BUYIN, QUICK_TYPE, SET_AMOUNT_BET_RAISE_BUTTON_1, SET_AMOUNT_BET_RAISE_BUTTON_2, SET_AMOUNT_BET_RAISE_BUTTON_3, SET_AMOUNT_BET_RAISE_BUTTON_4, SET_AMOUNT_BET_RAISE_BUTTON_5, SET_AMOUNT_BET_RAISE_BUTTON_6, SET_AMOUNT_BET_RAISE_BUTTON_7, SET_AMOUNT_BET_RAISE_FIVE_X_CALL, SET_AMOUNT_BET_RAISE_HALF_POT, SET_AMOUNT_BET_RAISE_MAX, SET_AMOUNT_BET_RAISE_POT, SET_AMOUNT_BET_RAISE_SLIDER_DEC, SET_AMOUNT_BET_RAISE_SLIDER_INC, SET_AMOUNT_BET_RAISE_THREE_FOURTH_POT, SET_AMOUNT_BET_RAISE_THREE_X_CALL, SET_AMOUNT_BET_RAISE_TWO_THIRD_POT, SET_AMOUNT_BET_RAISE_TWO_X_CALL, SHOW_STATS_BB_CASH, SHOW_STATS_BB_MTT, tablebg, tableouterbg, TABLE_BG, TABLE_OUTER_BG, TURN_HURRY_SOUND, TURN_SOUND, WINNING_SOUND
    }

    public enum PREFERENCES {
        //PREFERENCES Window--> cardplay_poker.cp_user_preferences
        user_id, avatar_id, game_layout_id, privacy_level, shared_info, modified_on, theme, sound_mute, show_hand_strength, show_hand_ranking, seatid_2_table, seatid_4_table, seatid_6_table, seatid_8_table, seatid_9_table, multi_run_allowed, vibrate_mode, auto_post_BB, four_color_deck, auto_muck, hide_empty_tables, hide_full_tables, is_config_view

    }

    public enum NOTES {
        // Notes Panel window-->   cardplay_poker.cp_user_notes
        user_id, opponent_id, note, is_active, color
    }

    public enum RAF {
        // cardplay_poker.cp_raf_referee_details

        referee_user_id, referrer_user_id, referral_code
    }


}
